# Blog info
blog_name: kylin
slogan: 醉里论道,醒时折花。
url: ruolinxue.github.io

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.jpg

# Set favicon
favicon: 

# For seo
keywords: kylin,前端,设计,Hexo主题,前端开发,用户体验,设计,frontend,design,nodejs,JavaScript

head_link:
  - type: Github
    icon: icon-github
    text_key: Github
    text_value_url: https://github.com/ruolinxue
    target_blank: true
  - type: weibo
    icon: icon-weibo1
    text_key: 新浪微博
    text_value_url:
    target_blank: true
  - type: Twitter
    icon: icon-twitter
    text_key: Twitter
    text_value_url:
    target_blank: true
  - type: facebook
    icon: icon-facebook1
    text_key: facebook
    text_value_url:
    target_blank: true

excerpt_link: 阅读全文

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #不在新页面打开
  # - name: Project
  #   url: /project/
  #   target_blank: true #在新页面打开
  - name: Github
    url: https://github.com/ruolinxue
    target_blank: true
  # - name: Twitter
  #   url: https://twitter.com/forsigner
  #   target_blank: true

# config page nav
page_nav:
  - name: 首页
    url: /
    target_blank: false # 不在新页面打开
    icon: icon-home
  - name: 归档
    url: /archives/
    target_blank: false # 不在新页面打开
    icon: icon-filing
  - name: 分类
    url: /categories/
    target_blank: false
    icon: icon-sort
  - name: 标签
    url: /tags/
    target_blank: false
    icon: icon-tag
  - name: 友链
    url: /link/
    target_blank: false
    icon: icon-link
  - name: RSS
    url: /atom.xml
    target_blank: true # 在新页面打开
    icon: icon-rss
  - name: 相册
    url: /album/
    target_blank: false # 在新页面打开
    icon: icon-image
  - name: 搜索
    url: /search/
    target_blank: false # 在新页面打开
    icon: icon-search

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
#toolbox:
#  isShow: true # true|fase
#  text: 盒子

search_slogan:
  isShow: true # true|fase
  text: Can you find the bug of world ~

link_slogan:
  isShow: false # true|fase
  text: 交换友链可以邮件

# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false


post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style
personal_style: /css/personal-style.css

home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics:
baidu_analytics: 57e94d016e201fba3603a8a2b0263af0

# Comment service
disqus_shortname: kylinz
# duoshuo_shortname: kylinz


# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "Scut，1991，Spring."
    - "喜欢设计，擅长编程，喜欢睡懒觉."
    - "前端开发工程师，常用 HTML / CSS / JavaScript."
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@kylin"
    text_value_url: https://github.com/ruolinxue

link:
  - name: 织网
    info: 身体和灵魂，总有一个在路上
    url: http://zheng-ji.info/
    avatar: https://avatars3.githubusercontent.com/u/1414745?v=3&s=100


